defaults: &defaults
  working_directory: ~/frampton
  docker:
    - image: circleci/node:6.10.3

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: npm-install
          command: npm install
      - run:
          name: npm-build
          command: npm run build
      - run:
          name: npm-test
          command: npm test

workflows:
  version: 2
  build_and_test:
      jobs:
        - test:
            filters:
              tags:
                only: /.*/